// 50 Iconic Anime Quotes & Cheer Notes for Parul University Students
// Formatted with BIG BOLD ROMAJI and clear English translations so students can read and understand effortlessly!

export const ANIME_CHEER_QUOTES = [
  {
    id: 'q-1',
    romaji: "SHINZO O SASAGEYO!",
    english: "Dedicate your heart with absolute conviction!",
    kanji: "心臓を捧げよ！",
    author: "Commander Erwin — Attack on Titan",
    badge: "⚔️ Titan Conqueror",
    color: "from-indigo-500 via-purple-600 to-slate-700",
    sfx: "⚡ Sasageyo~! (Dedicate Your Heart!)",
    voice: "Dedicate full focus to your 3-hour exam! Clear all doubts, cite core theories, and conquer the semester! 🛡️⚡"
  },
  {
    id: 'q-2',
    romaji: "NANA KOROBI YA OKI!",
    english: "Fall seven times, stand up eight!",
    kanji: "七転び八起き",
    author: "Japanese Classical Wisdom",
    badge: "🔥 Unyielding Spirit",
    color: "from-orange-500 via-red-500 to-pink-500",
    sfx: "💪 Ganbatte~! (Never Give Up!)",
    voice: "Even if a mock question or numerical feels tough, try again! Consistency creates absolute exam miracles! 🌸✨"
  },
  {
    id: 'q-3',
    romaji: "GENKAI O KOERO! IMA KOKO DE!",
    english: "Surpass your limits! Right here, right now!",
    kanji: "限界を超えろ！今ここで！",
    author: "Yami Sukehiro — Black Clover",
    badge: "⚡ Plus Ultra Spirit",
    color: "from-amber-400 via-orange-500 to-red-500",
    sfx: "💥 Genkai Toppa! (Surpass Limits!)",
    voice: "Push through that last chapter! You have the brains and the grit to crush this entire syllabus! 💥📚"
  },
  {
    id: 'q-4',
    romaji: "AKIRAMETARA SOKO DE SHIAI SHURYO DESU YO!",
    english: "If you give up now, the game is already over.",
    kanji: "諦めたらそこで試合終了ですよ",
    author: "Coach Anzai — Slam Dunk",
    badge: "🏆 Champion Mentality",
    color: "from-emerald-400 via-teal-500 to-cyan-500",
    sfx: "🏀 Katsu zo~! (Victory is Ours!)",
    voice: "Stay calm when reading Section C case studies. Break down the problem step-by-step and capture every mark! 🏀🎯"
  },
  {
    id: 'q-5',
    romaji: "KATSU MADE AKIRAMENAI, SORE GA ORE NO NINDO DA!",
    english: "Never giving up until I win — that is my ninja way!",
    kanji: "勝つまで諦めない、それが俺の忍道だ！",
    author: "Naruto Uzumaki — Naruto",
    badge: "🍥 Shinobi Determination",
    color: "from-orange-400 via-amber-500 to-yellow-500",
    sfx: "🍥 Dattebayo~! (Believe It!)",
    voice: "Believe it! You've prepared thoroughly with the AI squad. You have the exact knowledge needed to ace this test! 🍥⚔️"
  },
  {
    id: 'q-6',
    romaji: "PLUS ULTRA! SARA NI MUKO E!",
    english: "Go beyond, Plus Ultra!",
    kanji: "さらに向こうへ、Plus Ultra！",
    author: "All Might — My Hero Academia",
    badge: "🦸 Heroic Courage",
    color: "from-blue-500 via-indigo-500 to-violet-500",
    sfx: "🦸 Plus Ultra! (Go Beyond!)",
    voice: "Give your 100% and then give one more push! Outstanding marks are waiting for you! 🌟🦸‍♂️"
  },
  {
    id: 'q-7',
    romaji: "OMAE NO SHINJIRU, OMAE O SHINJIRO!",
    english: "Believe in the you that believes in yourself!",
    kanji: "お前の信じる、お前を信じろ！",
    author: "Kamina — Gurren Lagann",
    badge: "🔥 Unstoppable Drive",
    color: "from-red-500 via-rose-500 to-pink-500",
    sfx: "🔥 Gattai da~! (Unite and Fight!)",
    voice: "Trust your preparation. Even if an exam question looks scary, trust your instincts and knowledge! 🔥✨"
  },
  {
    id: 'q-8',
    romaji: "MIRAI WA IMA, KIMI NO TE NO NAKA NI ARU!",
    english: "The future is right here in your hands.",
    kanji: "未来は今、君の手の中にある",
    author: "Rintaro Okabe — Steins;Gate",
    badge: "🌌 Divergence 1.048%",
    color: "from-cyan-400 via-sky-500 to-blue-500",
    sfx: "⏱️ El Psy Kongroo! (Destiny Door)",
    voice: "Every minute of study recalibrates your future towards success! Top semester scores are in your destiny! ⏱️🌌"
  },
  {
    id: 'q-9',
    romaji: "KEIZOKU WA CHIKARA NARI!",
    english: "Continuity is power — Consistency breeds miracles.",
    kanji: "継続は力なり",
    author: "Classical Japanese Wisdom",
    badge: "💎 Supreme Mastery",
    color: "from-emerald-500 via-teal-500 to-cyan-500",
    sfx: "✨ Keizoku! (Keep Going!)",
    voice: "Studying 30 minutes every day beats 10 hours of panic cramming. You're building mastery block-by-block! 📚💎"
  },
  {
    id: 'q-10',
    romaji: "ICHIGO ICHIE!",
    english: "Treasure this moment — each encounter happens only once.",
    kanji: "一期一会",
    author: "Zen Philosophy",
    badge: "🌸 Zen Serenity",
    color: "from-pink-400 via-fuchsia-500 to-purple-500",
    sfx: "🌸 Kizuna~! (Deep Bond & Focus)",
    voice: "Take a deep breath and center your focus. Your preparation is your masterpiece — let it shine gracefully! 🍵🌸"
  },
  {
    id: 'q-11',
    romaji: "MAKERU NA! KOKO KARA GA HONBAN DA!",
    english: "Don't lose! The real battle starts right here!",
    kanji: "負けるな！ここからが本番だ！",
    author: "Tanjiro Kamado — Demon Slayer",
    badge: "⚔️ Hinokami Spirit",
    color: "from-red-600 via-orange-500 to-amber-500",
    sfx: "🌊 Total Concentration! (Zen Shuuchuu)",
    voice: "Total Concentration Breathing! Inhale confidence, exhale doubt, and answer with sharp logic! 🌊🗡️"
  },
  {
    id: 'q-12',
    romaji: "ORE WA KAIZOKU OU NI NARU OTOKO DA!",
    english: "I am the one who will become the Pirate King!",
    kanji: "海賊王に俺はなる！",
    author: "Monkey D. Luffy — One Piece",
    badge: "👑 King of Pirates",
    color: "from-red-500 via-amber-500 to-yellow-400",
    sfx: "🍖 Gomu Gomu no~! (Maximum Power!)",
    voice: "Aim for the highest grade in your batch! Don't settle for average when you can achieve greatness! 🍖👑"
  },
  {
    id: 'q-13',
    romaji: "RYOUKI TENKAI! MUGEN NO CHIKARA!",
    english: "Domain Expansion! Infinite knowledge unlocked!",
    kanji: "領域展開！無限の力！",
    author: "Satoru Gojo — Jujutsu Kaisen",
    badge: "👁️ Six Eyes Genius",
    color: "from-sky-400 via-indigo-500 to-blue-700",
    sfx: "🤞 Ryouki Tenkai! (Domain Expansion!)",
    voice: "Expand your exam domain! Lock in your 4-part blueprints and leave zero room for examiners to cut marks! 🤞🌌"
  },
  {
    id: 'q-14',
    romaji: "KURAIMAKKUSU WA KOKO KARA DA!",
    english: "The climax begins right now!",
    kanji: "クライマックスはここからだ！",
    author: "Shoto Todoroki — My Hero Academia",
    badge: "❄️🔥 Half-Cold Half-Hot",
    color: "from-cyan-400 via-purple-500 to-rose-500",
    sfx: "🔥 Flashfreeze Heatwave!",
    voice: "Balance your cool theoretical definitions with fiery practical case study applications! ❄️🔥"
  },
  {
    id: 'q-15',
    romaji: "OCHITARA AGARU DAKE DA!",
    english: "If you hit the bottom, the only way left is UP!",
    kanji: "落ちたら上がるだけだ！",
    author: "Shoyo Hinata — Haikyuu!!",
    badge: "🏐 Soaring Crow",
    color: "from-orange-500 via-amber-500 to-yellow-500",
    sfx: "🏐 Tobou! (Let's Fly!)",
    voice: "Past setbacks don't define your semester. Spread your wings, jump higher, and spike that exam paper! 🏐⚡"
  },
  {
    id: 'q-16',
    romaji: "BANKAI! SENBONZAKURA KAGEYOSHI!",
    english: "Bankai! Let your sharp knowledge blossom like a thousand blades!",
    kanji: "卍解！千本桜景厳！",
    author: "Byakuya Kuchiki — Bleach",
    badge: "🌸 Soul Reaper Captain",
    color: "from-pink-500 via-rose-600 to-purple-700",
    sfx: "🌸 Scatter! (Chire!)",
    voice: "Unleash your full potential! Scatter all confusion and write crisp, beautiful answers across the answer booklet! 🌸⚔️"
  },
  {
    id: 'q-17',
    romaji: "CHIKARA WA NOZOMU KARA DEWANAI, HITSUYOU DAKARA UMURERU NDA!",
    english: "Power comes in response to a need, not a desire!",
    kanji: "力は望むからではない、必要だから生まれるんだ！",
    author: "Goku — Dragon Ball Z",
    badge: "🐉 Super Saiyan",
    color: "from-yellow-400 via-amber-500 to-orange-500",
    sfx: "⚡ Kamehameha~! (Full Power!)",
    voice: "You need top grades to launch your dream career. Tap into that inner Super Saiyan focus right now! 🐉💥"
  },
  {
    id: 'q-18',
    romaji: "ME NO MAE NO KABE WA, KOERU TAME NI ARU!",
    english: "The wall in front of you exists solely to be overcome!",
    kanji: "目の前の壁は、越えるためにある！",
    author: "Tobio Kageyama — Haikyuu!!",
    badge: "👑 King of the Court",
    color: "from-blue-600 via-indigo-600 to-slate-800",
    sfx: "⚡ Precision Set! (Perfect Toss)",
    voice: "No question is too complex when you dissect it with clear subheadings, formulas, and diagrams! 🏐🎯"
  },
  {
    id: 'q-19',
    romaji: "DAIJOUBU! WATASHI WA SAIKYOU DAKARA!",
    english: "It's gonna be fine! After all, I'm the strongest!",
    kanji: "大丈夫！僕、最強だから！",
    author: "Satoru Gojo — Jujutsu Kaisen",
    badge: "🕶️ Limitless Confidence",
    color: "from-cyan-400 via-sky-500 to-indigo-600",
    sfx: "✨ Hollow Purple! (Muradaki)",
    voice: "Walk into that exam hall with 100% swagger and zero anxiety. You have prepared with 6 AI Professors! 🕶️💪"
  },
  {
    id: 'q-20',
    romaji: "YARE YARE DAZE...",
    english: "Good grief... Let's get this exam handled with zero fuss.",
    kanji: "やれやれだぜ...",
    author: "Jotaro Kujo — JoJo's Bizarre Adventure",
    badge: "⭐ Star Platinum Focus",
    color: "from-purple-600 via-indigo-600 to-zinc-800",
    sfx: "👊 ORA ORA ORA! (Rapid Answers)",
    voice: "Stop procrastinating! Pick up that pen, tackle Section A in 25 minutes, and roll smoothly through Section B! ⭐👊"
  },
  {
    id: 'q-21',
    romaji: "JIBUN O SHINJINAI YATSU NI, DORYOKU SURU KACHI WA NAI!",
    english: "If you don't believe in yourself, hard work is completely meaningless!",
    kanji: "自分を信じない奴なんかに、努力する価値はない！",
    author: "Might Guy — Naruto",
    badge: "🔥 Eight Gates of Youth",
    color: "from-emerald-500 via-teal-600 to-green-700",
    sfx: "🥋 Springtime of Youth! (Seishun Passion)",
    voice: "Have faith in your brain! Your late-night study hours will pay off tenfold on results day! 🔥🥋"
  },
  {
    id: 'q-22',
    romaji: "SEIKAI WA HITOTSU DEWA NAI!",
    english: "There is never just one correct path to the answer!",
    kanji: "正解は一つではない！",
    author: "L Lawliet — Death Note",
    badge: "🧠 Master Detective",
    color: "from-slate-600 via-zinc-700 to-gray-900",
    sfx: "🔍 Analytical Deduction!",
    voice: "In case study answers, present multi-dimensional perspectives: operational, financial, and strategic! 🔍☕"
  },
  {
    id: 'q-23',
    romaji: "KOKORO O MOYASE!",
    english: "Set your heart ablaze and push forward!",
    kanji: "心を燃やせ！",
    author: "Kyojuro Rengoku — Demon Slayer",
    badge: "🔥 Flame Hashira",
    color: "from-red-500 via-orange-500 to-amber-400",
    sfx: "🔥 Flame Breathing! (Honoo no Kokyuu)",
    voice: "Set your passion ablaze! When you write your answers, demonstrate genuine mastery and pride! 🔥🍱"
  },
  {
    id: 'q-24',
    romaji: "TATAKAE! TATAKAE!",
    english: "Fight! If you don't fight, you can't win!",
    kanji: "戦え！戦え！",
    author: "Eren Yeager — Attack on Titan",
    badge: "⚔️ Attack Titan",
    color: "from-emerald-600 via-teal-700 to-slate-900",
    sfx: "⚡ Tatakae! (Keep Fighting!)",
    voice: "Fight through fatigue, fight through distraction! That final degree certificate is waiting for you! ⚔️🔥"
  },
  {
    id: 'q-25',
    romaji: "GENKAI NADO NAI, ARU NO WA SUTOBA DA!",
    english: "There are no limits, only stopping points to surpass!",
    kanji: "限界などない！",
    author: "Vegeta — Dragon Ball Z",
    badge: "👑 Saiyan Prince",
    color: "from-blue-600 via-indigo-600 to-purple-600",
    sfx: "⚡ Final Flash! (Maximum Energy Beam)",
    voice: "Never settle for 60% when you have the capacity for 95%. Push past your self-imposed ceiling! 👑⚡"
  },
  {
    id: 'q-26',
    romaji: "SHINJIRU KARA KOSO, MICHI WA HIRAKERU!",
    english: "Because we believe, the path opens before us!",
    kanji: "信じるからこそ、道は開ける！",
    author: "Armin Arlert — Attack on Titan",
    badge: "🧭 Colossal Strategist",
    color: "from-sky-500 via-teal-500 to-emerald-600",
    sfx: "🧠 Strategic Breakthrough!",
    voice: "Smart strategy beats brute memorization. Use structured diagrams to capture full marks! 🧭💡"
  },
  {
    id: 'q-27',
    romaji: "KIMI GA INAKEREBA, KONO TABI WA HAJIMARANAKATTA!",
    english: "Without you taking action, this journey could never begin!",
    kanji: "君がいなければ始まらなかった！",
    author: "Edward Elric — Fullmetal Alchemist",
    badge: "⚗️ Fullmetal Alchemist",
    color: "from-amber-500 via-orange-600 to-red-600",
    sfx: "⚗️ Equivalent Exchange! (Touka Koukan)",
    voice: "The law of equivalent exchange: the effort you invest today returns as outstanding academic marks tomorrow! ⚗️✨"
  },
  {
    id: 'q-28',
    romaji: "YOWASA WA HAJI DEWA NAI, YOWAI MAMA IRU KOTO GA HAJI DA!",
    english: "Being weak is nothing to be ashamed of... Staying weak is!",
    kanji: "弱さは恥ではない、弱いままいることが恥だ！",
    author: "Fuegoleon Vermillion — Black Clover",
    badge: "🦁 Crimson Lion King",
    color: "from-orange-600 via-red-600 to-rose-700",
    sfx: "🦁 Roar of the Lion!",
    voice: "If you struggled with a previous mock test, learn from it right now! Use weak topic filters to conquer it! 🦁🔥"
  },
  {
    id: 'q-29',
    romaji: "CHOUJOU MADE TOMARU NA!",
    english: "Do not stop until you reach the very peak!",
    kanji: "頂上まで止まるな！",
    author: "Erza Scarlet — Fairy Tail",
    badge: "⚔️ Titania Blade",
    color: "from-rose-500 via-pink-600 to-purple-600",
    sfx: "⚔️ Requip Armor! (Instant Armor Swap)",
    voice: "Equip your mind with Dr. Divyanshu's Bloom's Taxonomy rubrics and answer every question like Titania! ⚔️🌸"
  },
  {
    id: 'q-30',
    romaji: "SHOURI WA, JUNBI O SHITA MONO NI HOMOE-KAKERU!",
    english: "Victory smiles upon those who prepare with precision!",
    kanji: "勝利は準備をした者に微笑む！",
    author: "Kuroko Tetsuya — Kuroko's Basketball",
    badge: "🏀 Phantom Ace",
    color: "from-cyan-400 via-sky-500 to-blue-600",
    sfx: "🏀 Ignite Pass! (Hyper Speed Pass)",
    voice: "Preparation eliminates surprise. When you know the format of Section A, B, and C, victory is guaranteed! 🏀🎯"
  },
  {
    id: 'q-31',
    romaji: "KIBOU WA SAIKOU NO WEAPON DA!",
    english: "Hope and relentless effort are the greatest weapons!",
    kanji: "希望は最高の武器だ！",
    author: "Simon — Gurren Lagann",
    badge: "🌀 Spiral Warrior",
    color: "from-blue-500 via-indigo-600 to-purple-600",
    sfx: "🌀 Giga Drill Break!",
    voice: "Drill right through confusing formulas! Break down complex equations into step-by-step additions! 🌀⚡"
  },
  {
    id: 'q-32',
    romaji: "KIMI WA KIMI NO HERO NI NARE!",
    english: "Be the hero of your own academic story!",
    kanji: "君は君のヒーローになれ！",
    author: "Izuku Midoriya (Deku) — My Hero Academia",
    badge: "📗 One For All Successor",
    color: "from-emerald-500 via-green-600 to-teal-700",
    sfx: "💥 Detroit Smash!",
    voice: "Write notes, analyze previous question papers, and believe in your personal growth every single day! 📗💪"
  },
  {
    id: 'q-33',
    romaji: "KIMI NO DORYOKU WA, KESHITE URAGIRANAI!",
    english: "Your honest effort will never betray you!",
    kanji: "君の努力は決して裏切らない！",
    author: "Rock Lee — Naruto",
    badge: "🥋 Splendid Ninja",
    color: "from-green-500 via-emerald-600 to-teal-600",
    sfx: "🥋 Primary Lotus! (Omote Renge)",
    voice: "Hard work beats raw talent when talent doesn't work hard! Keep revising your formula cheat sheet! 🥋🍃"
  },
  {
    id: 'q-34',
    romaji: "MUDA NA KOTO NADO, NANI HITOTSU NAI!",
    english: "Not a single moment of dedicated effort is ever wasted!",
    kanji: "無駄なことなど何一つない！",
    author: "Roy Mustang — Fullmetal Alchemist",
    badge: "🔥 Flame Alchemist",
    color: "from-blue-600 via-indigo-700 to-slate-900",
    sfx: "🔥 Snap of Ignition!",
    voice: "Every slide you reviewed and every question you practiced adds up to your final GPA! Keep snapping! 🔥✨"
  },
  {
    id: 'q-35',
    romaji: "SUKOSHI ZUTSU, MAE NI SUSUMOU!",
    english: "Step by step, keep moving steadily forward!",
    kanji: "少しずつ前に進もう！",
    author: "Tohru Honda — Fruits Basket",
    badge: "🌸 Gentle Heart",
    color: "from-pink-300 via-rose-400 to-fuchsia-500",
    sfx: "🌸 Yasashisa! (Kindness & Peace)",
    voice: "Take deep breaths. Don't overwhelm yourself trying to memorize everything at once. Focus on one topic at a time! 🌸🍵"
  },
  {
    id: 'q-36',
    romaji: "KIMI GA AKIRAMENAI KAGIRI, MICHI WA TSUDUKU!",
    english: "As long as you don't give up, your path continues!",
    kanji: "君が諦めない限り、道は続く！",
    author: "Gon Freecss — Hunter x Hunter",
    badge: "🎣 Nen Hunter",
    color: "from-emerald-400 via-green-500 to-teal-600",
    sfx: "🎣 Jajanken! (Rock Paper Scissors Strike)",
    voice: "Approach exam questions with honest curiosity and deep logic. You have incredible instinct! 🎣⭐"
  },
  {
    id: 'q-37',
    romaji: "MURI DATO OMOWARETA KOTO O NASHI-TOGERO!",
    english: "Achieve the very thing people thought was impossible!",
    kanji: "無理だと思われたことを成し遂げろ！",
    author: "Gintoki Sakata — Gintama",
    badge: "🍡 White Yaksha",
    color: "from-cyan-400 via-sky-500 to-slate-700",
    sfx: "🍡 Sugar Rush Power!",
    voice: "Shock everyone with your semester comeback! Review high-weightage topics and secure top marks! 🍡⚔️"
  },
  {
    id: 'q-38',
    romaji: "HONKI DE YAREBA, SUBETE GA KAWARU!",
    english: "When you put your true spirit into it, everything transforms!",
    kanji: "本気でやれば全てが変わる！",
    author: "Killua Zoldyck — Hunter x Hunter",
    badge: "⚡ Godspeed Lightning",
    color: "from-blue-400 via-indigo-500 to-violet-600",
    sfx: "⚡ Godspeed! (Lightning Speed Mode)",
    voice: "Activate Godspeed exam mode! Complete Section A in 20 minutes so you have plenty of time for Section C! ⚡🏃‍♂️"
  },
  {
    id: 'q-39',
    romaji: "JIBUN NO YAKUWARI O HATASE!",
    english: "Fulfill your mission with complete honor and pride!",
    kanji: "自分の役割を果たせ！",
    author: "Levi Ackerman — Attack on Titan",
    badge: "⚔️ Humanity's Strongest",
    color: "from-emerald-600 via-teal-700 to-zinc-800",
    sfx: "⚔️ Clean Slice! (Precision Blade Cut)",
    voice: "Eliminate all exam fluff and boilerplate. Write dense, high-mark keywords that examiners love! ⚔️☕"
  },
  {
    id: 'q-40',
    romaji: "KIMI NI DEKINAI KOTO WA NAI!",
    english: "There is nothing you cannot accomplish with focus!",
    kanji: "君にできないことはない！",
    author: "Senku Ishigami — Dr. Stone",
    badge: "🧪 10 Billion Percent Science",
    color: "from-emerald-400 via-green-500 to-lime-500",
    sfx: "🧪 10 Billion Percent! (10 Billion % Logic)",
    voice: "This is ten billion percent in your favor! Follow the scientific marking rubric and capture every mark! 🧪⚗️"
  },
  {
    id: 'q-41',
    romaji: "AYAMACHI O OSORERU NA, MANABE!",
    english: "Do not fear mistakes — learn from them and grow stronger!",
    kanji: "過ちを恐れるな、学べ！",
    author: "Kakashi Hatake — Naruto",
    badge: "👁️ Sharingan Sensei",
    color: "from-slate-500 via-zinc-600 to-gray-800",
    sfx: "⚡ Chidori! (One Thousand Birds)",
    voice: "Mistakes made during practice are blessings in disguise — they ensure you never repeat them in the actual exam! ⚡📖"
  },
  {
    id: 'q-42',
    romaji: "IKINOKORE! SOUSHITE KATSU NDA!",
    english: "Survive the pressure! And then emerge completely victorious!",
    kanji: "生き残れ！そして勝つんだ！",
    author: "Mikasa Ackerman — Attack on Titan",
    badge: "🧣 Guardian Blade",
    color: "from-rose-600 via-red-700 to-slate-900",
    sfx: "🧣 The World is Beautiful! (Utsukushii Sekai)",
    voice: "Keep your composure even when an unfamiliar case study appears. Break it down logically! 🧣🗡️"
  },
  {
    id: 'q-43',
    romaji: "KIMI NO POTENSHARU WA MUGENDAI!",
    english: "Your inner potential is literally limitless!",
    kanji: "君のポテンシャルは無限大！",
    author: "Kurama & Naruto — Naruto Shippuden",
    badge: "🦊 Nine Tails Synergy",
    color: "from-orange-500 via-amber-600 to-red-600",
    sfx: "🦊 Rasenshuriken!",
    voice: "Synergize all 6 AI agent blueprints with your uploaded syllabus for 100% exam readiness! 🦊🌀"
  },
  {
    id: 'q-44',
    romaji: "KOKO DE OWARASENAI, MAE O MUITE SUSUME!",
    english: "This is not where it ends — look ahead and keep charging!",
    kanji: "前を向いて進め！",
    author: "Natsu Dragneel — Fairy Tail",
    badge: "🔥 Fire Dragon Slayer",
    color: "from-red-500 via-orange-500 to-amber-500",
    sfx: "🔥 Fire Dragon Roar!",
    voice: "Ignite your academic passion! Write your descriptive answers with conviction and vivid clarity! 🔥🐉"
  },
  {
    id: 'q-45',
    romaji: "SUTORIITO NO TEIOU TO NARE!",
    english: "Become the undisputed master of your subject domain!",
    kanji: "帝王となれ！",
    author: "Seijuro Akashi — Kuroko's Basketball",
    badge: "👁️ Emperor Eye",
    color: "from-red-600 via-rose-700 to-purple-800",
    sfx: "👁️ Ankle Break! (Absolute Victory)",
    voice: "With the Emperor Eye of our Exam Predictor, see through the examiner's tricks before they even ask! 👁️🏀"
  },
  {
    id: 'q-46',
    romaji: "KIMI WA HITORI DEWA NAI!",
    english: "You are never alone on this academic journey!",
    kanji: "君は一人ではない！",
    author: "Aki & Rohan Mitra — Parul Study Assistant",
    badge: "🌸 Study Companion",
    color: "from-pink-500 via-purple-600 to-indigo-600",
    sfx: "💖 Ganbatte Kudasai! (We Believe in You!)",
    voice: "Aki, Rohan Mitra, and all 6 AI Professors are standing right beside you! You have everything you need to ace this! 🌸💖"
  },
  {
    id: 'q-47',
    romaji: "SHUKUDAI MO TESUTO MO, ZENBU KURIA SHITE MISERU!",
    english: "Assignments or semester exams — clear every single one with full marks!",
    kanji: "全部クリアしてみせる！",
    author: "Kirito — Sword Art Online",
    badge: "⚔️ Black Swordsman",
    color: "from-slate-700 via-zinc-800 to-black",
    sfx: "⚔️ Starburst Stream! (16-Hit Combo)",
    voice: "Dual-wield your theoretical mastery and quantitative speed to finish your paper with 20 minutes to spare! ⚔️⚡"
  },
  {
    id: 'q-48',
    romaji: "JIBUN GA ERANDA MICHI O HOKORE!",
    english: "Take pride in the academic path you have chosen!",
    kanji: "誇りを持て！",
    author: "Kenpachi Zaraki — Bleach",
    badge: "⚔️ Unstoppable Captain",
    color: "from-amber-600 via-orange-700 to-zinc-900",
    sfx: "⚔️ Pure Spiritual Pressure!",
    voice: "Hold your head high! You have studied diligently, and your university results will reflect your true power! ⚔️💥"
  },
  {
    id: 'q-49',
    romaji: "KIMI NO YUME WA, KANARAZU KANAU!",
    english: "Your dreams will without question become your reality!",
    kanji: "夢は必ず叶う！",
    author: "Aki (秋) — Google Antigravity Study Agent",
    badge: "🌟 Destiny Fulfilled",
    color: "from-pink-400 via-purple-500 to-indigo-500",
    sfx: "✨ Yume wa Kanau! (Dreams Come True!)",
    voice: "Every hour of studying is building the foundation for your brilliant career. Keep pushing, champion! 🌟🎓"
  },
  {
    id: 'q-50',
    romaji: "SAIKOU NO KEKKA O TSUKAMI-TORE!",
    english: "Seize the absolute highest result with both hands!",
    kanji: "最高の結果を掴み取れ！",
    author: "Parul University AI Squad",
    badge: "🏆 100% Semester Ace",
    color: "from-emerald-400 via-teal-500 to-indigo-600",
    sfx: "🎉 Kanpeki! (Absolute Perfection!)",
    voice: "Step into the examination hall with full confidence! You are 100% prepared to claim top marks! 🏆🎓✨"
  }
];
